{% set name = "microsoft-kiota-abstractions" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_abstractions-{{ version }}.tar.gz
  sha256: 3cc01832a2e6dc6094c4e1abf7cbef3849a87d818a3b9193ad6c83a9f88e14ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - std-uritemplate >=0.0.38
    - opentelemetry-api >=1.19.0
    - opentelemetry-sdk >=1.19.0

test:
  imports:
    - kiota_abstractions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-abstractions-python
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-abstractions-python
  doc_url: https://github.com/microsoft/kiota-abstractions-python/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
